export const CREATE_BLOOD_GROUP = "CREATE_BLOOD_GROUP";
export const RETRIEVE_BLOOD_GROUPS = "RETRIEVE_BLOOD_GROUPS";
export const UPDATE_BLOOD_GROUP = "UPDATE_BLOOD_GROUP";
export const DELETE_BLOOD_GROUP = "DELETE_BLOOD_GROUP";
export const DELETE_ALL_BLOOD_GROUPS = "DELETE_ALL_BLOOD_GROUPS";